# FCA

In [1]:
import numpy as np
import pandas as pd

### My data

In [2]:
columns_name = np.array([
        'mod_zurix',             # 1. Код для класса (модифицированный класс Цюриха) (A, B, C, D, E, F, H)
        'largest_spot',          # 2. Код для наибольшего размера пятна (X, R, S, A, H, K)
        'spot_distribution',     # 3. Код для пятна распределение (X, O, I, C)
        'activity',              # 4. Активность (1 = уменьшенная, 2 = неизменная)
        'evolution',             # 5. Эволюция (1 = распад, 2 = отсутствие роста, 3 = рост)
        'activity_last_24',      # 6. Предыдущий 24-часовой код активности вспышки (1 = ничто так велико, как M1, 2 = один M1, 3 = больше активности, чем один M1)
        'historically_complex',  # 7. Исторически сложный (1 = Да, 2 = Нет)
        'suns_disk',             # 8. Стал ли исторически сложным регион на этом проходе через солнечный диск (1 = да, 2 = нет)
        'area',                  # 9. Площадь (1 = маленькая, 2 = большая)
        'area_largest_spot',     # 10.Площадь наибольшего пятна (1 = <= 5, 2 => 5)
        'common_flares',         # 11.обычные вспышки
        'moderate_flares',       # 12.умеренные вспышки
        'severe_flares'          # 13.Сильные вспышки
    ]) 


f = open("./data/flare.data2","r")

data = [ a.strip().split(" ") for a in f][1:]
df = pd.DataFrame(np.array(data), columns=columns_name)  
df = df.drop('moderate_flares', axis='columns')
df = df.drop('severe_flares', axis='columns')

In [3]:
def binarization_data_frame(df, column, array):
    for i in array:
        df[column + '_' + str(i)] = df[df[column] == i][column]
        df[column + '_' + str(i)][df[column + '_' + str(i)] == i] = 1
        df[column + '_' + str(i)] = df[column + '_' + str(i)].fillna(value=2)
    
    df = df.drop(column, axis='columns')
    return df

In [4]:
mod_zurix         = ['A', 'B', 'C', 'D', 'E', 'F', 'H']
largest_spot      = ['X', 'R', 'S', 'A', 'H', 'K']
spot_distribution = ['X', 'O', 'I', 'C']
evolution         = ['1', '2', '3']
activity_last_24  = ['1', '2', '3']

In [5]:
df = binarization_data_frame(df, 'mod_zurix', mod_zurix)
df = binarization_data_frame(df, 'largest_spot', largest_spot)
df = binarization_data_frame(df, 'spot_distribution', spot_distribution)
df = binarization_data_frame(df, 'evolution', evolution)
df = binarization_data_frame(df, 'activity_last_24', activity_last_24)

c:\users\alkzir\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [6]:
df['common_flares'] = df['common_flares'].replace(['2', '3', '4', '5', '6', '7', '8'], '1')
df['common_flares'] = df['common_flares'].replace(['0'], '2')

In [7]:
df['common_flares'].value_counts()

2    884
1    182
Name: common_flares, dtype: int64

In [8]:
df

,activity,historically_complex,suns_disk,area,area_largest_spot,common_flares,mod_zurix_A,mod_zurix_B,mod_zurix_C,mod_zurix_D,...,spot_distribution_X,spot_distribution_O,spot_distribution_I,spot_distribution_C,evolution_1,evolution_2,evolution_3,activity_last_24_1,activity_last_24_2,activity_last_24_3
0,1,1,1,1,1,2,2,2,2,2,...,1,2,2,2,2,2,1,1,2,2
1,1,1,2,1,1,2,2,2,2,1,...,2,1,2,2,2,2,1,1,2,2
2,1,1,2,1,1,2,2,2,1,2,...,2,1,2,2,2,2,1,1,2,2
3,1,1,1,1,1,2,2,2,2,2,...,1,2,2,2,2,1,2,1,2,2
4,1,1,2,1,1,2,2,2,2,2,...,1,2,2,2,1,2,2,1,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1061,1,1,1,1,1,2,2,2,2,2,...,1,2,2,2,2,1,2,1,2,2
1062,2,1,2,1,1,2,2,2,2,2,...,1,2,2,2,2,1,2,1,2,2
1063,1,2,2,1,1,2,2,2,1,2,...,2,1,2,2,2,1,2,1,2,2
1064,1,1,2,1,1,2,2,2,2,2,...,1,2,2,2,2,1,2,1,2,2
1065,1,1,2,1,1,2,2,1,2,2,...,2,1,2,2,1,2,2,1,2,2

In [9]:
df = df.drop_duplicates()
df.shape

(315, 29)

In [10]:
# export_csv = df.to_csv (r'C:\Users\Alkzir\AppData\Local\Programs\Python\Python37-32\Scripts\FCA\data\train.csv', index = None, header=True)